name: Adabelle Tan
favicon: null
layout_spectrum: 0.1472
typography_spectrum: 0.53241
title: The Portfolio of Adabelle Tan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#201f1d'
    - '#cac7b8'
    - '#9b998d'
    - '#7e7b72'
    - '#53524d'
  brandStrength: 0.6875
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
